apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-non-root
spec:
  containers:
  - name: main
    image: alpine:3.19
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsNonRoot: true
