apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccountName: default
  containers:
  - name: main
    image: curlimages/curl:8.12.1
    command: ["sleep", "9999999"]
  - name: ambassador
    image: k8sschool/kubectl-proxy:1.27.3
