apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  containers:
  - name: main
    image: curlimages/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: k8sschool/kubectl-proxy:1.27.3
