apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    enable-admission-plugins: AlwaysPullImages,DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    token-auth-file: /etc/kubernetes/auth/tokens.csv
  extraVolumes:
  - hostPath: /etc/kubernetes/auth
    mountPath: /etc/kubernetes/auth
    name: tokens
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
kubernetesVersion: v1.32.7
# Current version:
# kubernetesVersion: v1.26.1
