apiServer:
  extraArgs:
  - name: enable-admission-plugins
    value: AlwaysPullImages,DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
  - name: token-auth-file
    value: /etc/kubernetes/auth/tokens.csv
  extraVolumes:
  - hostPath: /etc/kubernetes/auth
    mountPath: /etc/kubernetes/auth
    name: tokens
apiVersion: kubeadm.k8s.io/v1beta4
clusterName: kubernetes
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.32.7
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
